// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: paxoskv.proto

#include "paxoskv.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace paxoskv {
class GetReqDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<GetReq>
      _instance;
} _GetReq_default_instance_;
class GetRespDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<GetResp>
      _instance;
} _GetResp_default_instance_;
class SetReqDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<SetReq>
      _instance;
} _SetReq_default_instance_;
class SetRespDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<SetResp>
      _instance;
} _SetResp_default_instance_;
class DelReqDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<DelReq>
      _instance;
} _DelReq_default_instance_;
class DelRespDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<DelResp>
      _instance;
} _DelResp_default_instance_;
}  // namespace paxoskv
namespace protobuf_paxoskv_2eproto {
static void InitDefaultsGetReq() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::paxoskv::_GetReq_default_instance_;
    new (ptr) ::paxoskv::GetReq();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::paxoskv::GetReq::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_GetReq =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsGetReq}, {}};

static void InitDefaultsGetResp() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::paxoskv::_GetResp_default_instance_;
    new (ptr) ::paxoskv::GetResp();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::paxoskv::GetResp::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_GetResp =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsGetResp}, {}};

static void InitDefaultsSetReq() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::paxoskv::_SetReq_default_instance_;
    new (ptr) ::paxoskv::SetReq();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::paxoskv::SetReq::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_SetReq =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsSetReq}, {}};

static void InitDefaultsSetResp() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::paxoskv::_SetResp_default_instance_;
    new (ptr) ::paxoskv::SetResp();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::paxoskv::SetResp::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_SetResp =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsSetResp}, {}};

static void InitDefaultsDelReq() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::paxoskv::_DelReq_default_instance_;
    new (ptr) ::paxoskv::DelReq();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::paxoskv::DelReq::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_DelReq =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsDelReq}, {}};

static void InitDefaultsDelResp() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::paxoskv::_DelResp_default_instance_;
    new (ptr) ::paxoskv::DelResp();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::paxoskv::DelResp::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_DelResp =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsDelResp}, {}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_GetReq.base);
  ::google::protobuf::internal::InitSCC(&scc_info_GetResp.base);
  ::google::protobuf::internal::InitSCC(&scc_info_SetReq.base);
  ::google::protobuf::internal::InitSCC(&scc_info_SetResp.base);
  ::google::protobuf::internal::InitSCC(&scc_info_DelReq.base);
  ::google::protobuf::internal::InitSCC(&scc_info_DelResp.base);
}

::google::protobuf::Metadata file_level_metadata[6];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::paxoskv::GetReq, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::paxoskv::GetReq, key_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::paxoskv::GetResp, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::paxoskv::GetResp, value_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::paxoskv::SetReq, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::paxoskv::SetReq, key_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::paxoskv::SetReq, value_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::paxoskv::SetResp, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::paxoskv::DelReq, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::paxoskv::DelReq, key_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::paxoskv::DelResp, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::paxoskv::GetReq)},
  { 6, -1, sizeof(::paxoskv::GetResp)},
  { 12, -1, sizeof(::paxoskv::SetReq)},
  { 19, -1, sizeof(::paxoskv::SetResp)},
  { 24, -1, sizeof(::paxoskv::DelReq)},
  { 30, -1, sizeof(::paxoskv::DelResp)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::paxoskv::_GetReq_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::paxoskv::_GetResp_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::paxoskv::_SetReq_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::paxoskv::_SetResp_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::paxoskv::_DelReq_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::paxoskv::_DelResp_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "paxoskv.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 6);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\rpaxoskv.proto\022\007paxoskv\"\025\n\006GetReq\022\013\n\003ke"
      "y\030\001 \001(\014\"\030\n\007GetResp\022\r\n\005value\030\001 \001(\014\"$\n\006Set"
      "Req\022\013\n\003key\030\001 \001(\014\022\r\n\005value\030\002 \001(\014\"\t\n\007SetRe"
      "sp\"\025\n\006DelReq\022\013\n\003key\030\001 \001(\014\"\t\n\007DelResp2\216\001\n"
      "\016PaxosKVService\022(\n\003Get\022\017.paxoskv.GetReq\032"
      "\020.paxoskv.GetResp\022(\n\003Set\022\017.paxoskv.SetRe"
      "q\032\020.paxoskv.SetResp\022(\n\003Del\022\017.paxoskv.Del"
      "Req\032\020.paxoskv.DelRespb\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 309);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "paxoskv.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_paxoskv_2eproto
namespace paxoskv {

// ===================================================================

void GetReq::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int GetReq::kKeyFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

GetReq::GetReq()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_paxoskv_2eproto::scc_info_GetReq.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:paxoskv.GetReq)
}
GetReq::GetReq(const GetReq& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  key_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.key().size() > 0) {
    key_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.key_);
  }
  // @@protoc_insertion_point(copy_constructor:paxoskv.GetReq)
}

void GetReq::SharedCtor() {
  key_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

GetReq::~GetReq() {
  // @@protoc_insertion_point(destructor:paxoskv.GetReq)
  SharedDtor();
}

void GetReq::SharedDtor() {
  key_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void GetReq::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* GetReq::descriptor() {
  ::protobuf_paxoskv_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_paxoskv_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const GetReq& GetReq::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_paxoskv_2eproto::scc_info_GetReq.base);
  return *internal_default_instance();
}


void GetReq::Clear() {
// @@protoc_insertion_point(message_clear_start:paxoskv.GetReq)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  key_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

bool GetReq::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:paxoskv.GetReq)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // bytes key = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_key()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:paxoskv.GetReq)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:paxoskv.GetReq)
  return false;
#undef DO_
}

void GetReq::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:paxoskv.GetReq)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bytes key = 1;
  if (this->key().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      1, this->key(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:paxoskv.GetReq)
}

::google::protobuf::uint8* GetReq::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:paxoskv.GetReq)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bytes key = 1;
  if (this->key().size() > 0) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        1, this->key(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:paxoskv.GetReq)
  return target;
}

size_t GetReq::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:paxoskv.GetReq)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // bytes key = 1;
  if (this->key().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->key());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void GetReq::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:paxoskv.GetReq)
  GOOGLE_DCHECK_NE(&from, this);
  const GetReq* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const GetReq>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:paxoskv.GetReq)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:paxoskv.GetReq)
    MergeFrom(*source);
  }
}

void GetReq::MergeFrom(const GetReq& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:paxoskv.GetReq)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.key().size() > 0) {

    key_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.key_);
  }
}

void GetReq::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:paxoskv.GetReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void GetReq::CopyFrom(const GetReq& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:paxoskv.GetReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GetReq::IsInitialized() const {
  return true;
}

void GetReq::Swap(GetReq* other) {
  if (other == this) return;
  InternalSwap(other);
}
void GetReq::InternalSwap(GetReq* other) {
  using std::swap;
  key_.Swap(&other->key_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata GetReq::GetMetadata() const {
  protobuf_paxoskv_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_paxoskv_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void GetResp::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int GetResp::kValueFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

GetResp::GetResp()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_paxoskv_2eproto::scc_info_GetResp.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:paxoskv.GetResp)
}
GetResp::GetResp(const GetResp& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  value_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.value().size() > 0) {
    value_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.value_);
  }
  // @@protoc_insertion_point(copy_constructor:paxoskv.GetResp)
}

void GetResp::SharedCtor() {
  value_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

GetResp::~GetResp() {
  // @@protoc_insertion_point(destructor:paxoskv.GetResp)
  SharedDtor();
}

void GetResp::SharedDtor() {
  value_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void GetResp::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* GetResp::descriptor() {
  ::protobuf_paxoskv_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_paxoskv_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const GetResp& GetResp::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_paxoskv_2eproto::scc_info_GetResp.base);
  return *internal_default_instance();
}


void GetResp::Clear() {
// @@protoc_insertion_point(message_clear_start:paxoskv.GetResp)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  value_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

bool GetResp::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:paxoskv.GetResp)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // bytes value = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_value()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:paxoskv.GetResp)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:paxoskv.GetResp)
  return false;
#undef DO_
}

void GetResp::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:paxoskv.GetResp)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bytes value = 1;
  if (this->value().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      1, this->value(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:paxoskv.GetResp)
}

::google::protobuf::uint8* GetResp::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:paxoskv.GetResp)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bytes value = 1;
  if (this->value().size() > 0) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        1, this->value(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:paxoskv.GetResp)
  return target;
}

size_t GetResp::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:paxoskv.GetResp)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // bytes value = 1;
  if (this->value().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->value());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void GetResp::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:paxoskv.GetResp)
  GOOGLE_DCHECK_NE(&from, this);
  const GetResp* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const GetResp>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:paxoskv.GetResp)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:paxoskv.GetResp)
    MergeFrom(*source);
  }
}

void GetResp::MergeFrom(const GetResp& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:paxoskv.GetResp)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.value().size() > 0) {

    value_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.value_);
  }
}

void GetResp::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:paxoskv.GetResp)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void GetResp::CopyFrom(const GetResp& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:paxoskv.GetResp)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GetResp::IsInitialized() const {
  return true;
}

void GetResp::Swap(GetResp* other) {
  if (other == this) return;
  InternalSwap(other);
}
void GetResp::InternalSwap(GetResp* other) {
  using std::swap;
  value_.Swap(&other->value_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata GetResp::GetMetadata() const {
  protobuf_paxoskv_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_paxoskv_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void SetReq::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int SetReq::kKeyFieldNumber;
const int SetReq::kValueFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

SetReq::SetReq()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_paxoskv_2eproto::scc_info_SetReq.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:paxoskv.SetReq)
}
SetReq::SetReq(const SetReq& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  key_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.key().size() > 0) {
    key_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.key_);
  }
  value_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.value().size() > 0) {
    value_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.value_);
  }
  // @@protoc_insertion_point(copy_constructor:paxoskv.SetReq)
}

void SetReq::SharedCtor() {
  key_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  value_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

SetReq::~SetReq() {
  // @@protoc_insertion_point(destructor:paxoskv.SetReq)
  SharedDtor();
}

void SetReq::SharedDtor() {
  key_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  value_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void SetReq::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* SetReq::descriptor() {
  ::protobuf_paxoskv_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_paxoskv_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const SetReq& SetReq::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_paxoskv_2eproto::scc_info_SetReq.base);
  return *internal_default_instance();
}


void SetReq::Clear() {
// @@protoc_insertion_point(message_clear_start:paxoskv.SetReq)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  key_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  value_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

bool SetReq::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:paxoskv.SetReq)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // bytes key = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_key()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bytes value = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_value()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:paxoskv.SetReq)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:paxoskv.SetReq)
  return false;
#undef DO_
}

void SetReq::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:paxoskv.SetReq)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bytes key = 1;
  if (this->key().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      1, this->key(), output);
  }

  // bytes value = 2;
  if (this->value().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      2, this->value(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:paxoskv.SetReq)
}

::google::protobuf::uint8* SetReq::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:paxoskv.SetReq)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bytes key = 1;
  if (this->key().size() > 0) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        1, this->key(), target);
  }

  // bytes value = 2;
  if (this->value().size() > 0) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        2, this->value(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:paxoskv.SetReq)
  return target;
}

size_t SetReq::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:paxoskv.SetReq)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // bytes key = 1;
  if (this->key().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->key());
  }

  // bytes value = 2;
  if (this->value().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->value());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void SetReq::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:paxoskv.SetReq)
  GOOGLE_DCHECK_NE(&from, this);
  const SetReq* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const SetReq>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:paxoskv.SetReq)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:paxoskv.SetReq)
    MergeFrom(*source);
  }
}

void SetReq::MergeFrom(const SetReq& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:paxoskv.SetReq)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.key().size() > 0) {

    key_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.key_);
  }
  if (from.value().size() > 0) {

    value_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.value_);
  }
}

void SetReq::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:paxoskv.SetReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SetReq::CopyFrom(const SetReq& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:paxoskv.SetReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SetReq::IsInitialized() const {
  return true;
}

void SetReq::Swap(SetReq* other) {
  if (other == this) return;
  InternalSwap(other);
}
void SetReq::InternalSwap(SetReq* other) {
  using std::swap;
  key_.Swap(&other->key_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  value_.Swap(&other->value_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata SetReq::GetMetadata() const {
  protobuf_paxoskv_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_paxoskv_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void SetResp::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

SetResp::SetResp()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_paxoskv_2eproto::scc_info_SetResp.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:paxoskv.SetResp)
}
SetResp::SetResp(const SetResp& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:paxoskv.SetResp)
}

void SetResp::SharedCtor() {
}

SetResp::~SetResp() {
  // @@protoc_insertion_point(destructor:paxoskv.SetResp)
  SharedDtor();
}

void SetResp::SharedDtor() {
}

void SetResp::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* SetResp::descriptor() {
  ::protobuf_paxoskv_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_paxoskv_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const SetResp& SetResp::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_paxoskv_2eproto::scc_info_SetResp.base);
  return *internal_default_instance();
}


void SetResp::Clear() {
// @@protoc_insertion_point(message_clear_start:paxoskv.SetResp)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _internal_metadata_.Clear();
}

bool SetResp::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:paxoskv.SetResp)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
  handle_unusual:
    if (tag == 0) {
      goto success;
    }
    DO_(::google::protobuf::internal::WireFormat::SkipField(
          input, tag, _internal_metadata_.mutable_unknown_fields()));
  }
success:
  // @@protoc_insertion_point(parse_success:paxoskv.SetResp)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:paxoskv.SetResp)
  return false;
#undef DO_
}

void SetResp::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:paxoskv.SetResp)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:paxoskv.SetResp)
}

::google::protobuf::uint8* SetResp::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:paxoskv.SetResp)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:paxoskv.SetResp)
  return target;
}

size_t SetResp::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:paxoskv.SetResp)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void SetResp::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:paxoskv.SetResp)
  GOOGLE_DCHECK_NE(&from, this);
  const SetResp* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const SetResp>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:paxoskv.SetResp)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:paxoskv.SetResp)
    MergeFrom(*source);
  }
}

void SetResp::MergeFrom(const SetResp& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:paxoskv.SetResp)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

}

void SetResp::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:paxoskv.SetResp)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SetResp::CopyFrom(const SetResp& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:paxoskv.SetResp)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SetResp::IsInitialized() const {
  return true;
}

void SetResp::Swap(SetResp* other) {
  if (other == this) return;
  InternalSwap(other);
}
void SetResp::InternalSwap(SetResp* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata SetResp::GetMetadata() const {
  protobuf_paxoskv_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_paxoskv_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void DelReq::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int DelReq::kKeyFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

DelReq::DelReq()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_paxoskv_2eproto::scc_info_DelReq.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:paxoskv.DelReq)
}
DelReq::DelReq(const DelReq& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  key_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.key().size() > 0) {
    key_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.key_);
  }
  // @@protoc_insertion_point(copy_constructor:paxoskv.DelReq)
}

void DelReq::SharedCtor() {
  key_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

DelReq::~DelReq() {
  // @@protoc_insertion_point(destructor:paxoskv.DelReq)
  SharedDtor();
}

void DelReq::SharedDtor() {
  key_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void DelReq::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* DelReq::descriptor() {
  ::protobuf_paxoskv_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_paxoskv_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const DelReq& DelReq::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_paxoskv_2eproto::scc_info_DelReq.base);
  return *internal_default_instance();
}


void DelReq::Clear() {
// @@protoc_insertion_point(message_clear_start:paxoskv.DelReq)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  key_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

bool DelReq::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:paxoskv.DelReq)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // bytes key = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_key()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:paxoskv.DelReq)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:paxoskv.DelReq)
  return false;
#undef DO_
}

void DelReq::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:paxoskv.DelReq)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bytes key = 1;
  if (this->key().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      1, this->key(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:paxoskv.DelReq)
}

::google::protobuf::uint8* DelReq::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:paxoskv.DelReq)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bytes key = 1;
  if (this->key().size() > 0) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        1, this->key(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:paxoskv.DelReq)
  return target;
}

size_t DelReq::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:paxoskv.DelReq)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // bytes key = 1;
  if (this->key().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->key());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void DelReq::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:paxoskv.DelReq)
  GOOGLE_DCHECK_NE(&from, this);
  const DelReq* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const DelReq>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:paxoskv.DelReq)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:paxoskv.DelReq)
    MergeFrom(*source);
  }
}

void DelReq::MergeFrom(const DelReq& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:paxoskv.DelReq)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.key().size() > 0) {

    key_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.key_);
  }
}

void DelReq::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:paxoskv.DelReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void DelReq::CopyFrom(const DelReq& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:paxoskv.DelReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DelReq::IsInitialized() const {
  return true;
}

void DelReq::Swap(DelReq* other) {
  if (other == this) return;
  InternalSwap(other);
}
void DelReq::InternalSwap(DelReq* other) {
  using std::swap;
  key_.Swap(&other->key_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata DelReq::GetMetadata() const {
  protobuf_paxoskv_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_paxoskv_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void DelResp::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

DelResp::DelResp()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_paxoskv_2eproto::scc_info_DelResp.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:paxoskv.DelResp)
}
DelResp::DelResp(const DelResp& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:paxoskv.DelResp)
}

void DelResp::SharedCtor() {
}

DelResp::~DelResp() {
  // @@protoc_insertion_point(destructor:paxoskv.DelResp)
  SharedDtor();
}

void DelResp::SharedDtor() {
}

void DelResp::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* DelResp::descriptor() {
  ::protobuf_paxoskv_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_paxoskv_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const DelResp& DelResp::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_paxoskv_2eproto::scc_info_DelResp.base);
  return *internal_default_instance();
}


void DelResp::Clear() {
// @@protoc_insertion_point(message_clear_start:paxoskv.DelResp)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _internal_metadata_.Clear();
}

bool DelResp::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:paxoskv.DelResp)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
  handle_unusual:
    if (tag == 0) {
      goto success;
    }
    DO_(::google::protobuf::internal::WireFormat::SkipField(
          input, tag, _internal_metadata_.mutable_unknown_fields()));
  }
success:
  // @@protoc_insertion_point(parse_success:paxoskv.DelResp)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:paxoskv.DelResp)
  return false;
#undef DO_
}

void DelResp::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:paxoskv.DelResp)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:paxoskv.DelResp)
}

::google::protobuf::uint8* DelResp::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:paxoskv.DelResp)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:paxoskv.DelResp)
  return target;
}

size_t DelResp::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:paxoskv.DelResp)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void DelResp::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:paxoskv.DelResp)
  GOOGLE_DCHECK_NE(&from, this);
  const DelResp* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const DelResp>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:paxoskv.DelResp)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:paxoskv.DelResp)
    MergeFrom(*source);
  }
}

void DelResp::MergeFrom(const DelResp& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:paxoskv.DelResp)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

}

void DelResp::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:paxoskv.DelResp)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void DelResp::CopyFrom(const DelResp& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:paxoskv.DelResp)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DelResp::IsInitialized() const {
  return true;
}

void DelResp::Swap(DelResp* other) {
  if (other == this) return;
  InternalSwap(other);
}
void DelResp::InternalSwap(DelResp* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata DelResp::GetMetadata() const {
  protobuf_paxoskv_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_paxoskv_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace paxoskv
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::paxoskv::GetReq* Arena::CreateMaybeMessage< ::paxoskv::GetReq >(Arena* arena) {
  return Arena::CreateInternal< ::paxoskv::GetReq >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::paxoskv::GetResp* Arena::CreateMaybeMessage< ::paxoskv::GetResp >(Arena* arena) {
  return Arena::CreateInternal< ::paxoskv::GetResp >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::paxoskv::SetReq* Arena::CreateMaybeMessage< ::paxoskv::SetReq >(Arena* arena) {
  return Arena::CreateInternal< ::paxoskv::SetReq >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::paxoskv::SetResp* Arena::CreateMaybeMessage< ::paxoskv::SetResp >(Arena* arena) {
  return Arena::CreateInternal< ::paxoskv::SetResp >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::paxoskv::DelReq* Arena::CreateMaybeMessage< ::paxoskv::DelReq >(Arena* arena) {
  return Arena::CreateInternal< ::paxoskv::DelReq >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::paxoskv::DelResp* Arena::CreateMaybeMessage< ::paxoskv::DelResp >(Arena* arena) {
  return Arena::CreateInternal< ::paxoskv::DelResp >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
